name: rojgar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0
  equatable: ^2.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  flutter_riverpod: ^2.3.6
  dartz: ^0.10.1
  uuid: ^4.5.2
  shared_preferences: ^2.5.4
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  flutter_bloc: ^8.1.5

  # Networking
  dio: ^5.4.3
  pretty_dio_logger: ^1.2.0
  flutter_secure_storage: 10.0.0
  connectivity_plus: ^7.0.0
  dio_smart_retry: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons:  ^0.14.4
  mockito: ^5.4.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    
    
flutter_launcher_icons:
  android: "luncher_icons"
  iso: "AppIcon"
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

